version: "3.8"

services:
   mysql_server:
     image: mysql
     networks:
       - backend
     environment:
       - MYSQL_DATABASE=test_db
       - MYSQL_USER=dan
       - MYSQL_PASSWORD=secret
       - MYSQL_ROOT_PASSWORD=root
     ports:
       - "3306:3306"
networks:
  backend:
